version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app:cached
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
      NEXT_TELEMETRY_DISABLED: 1
    command: pnpm dev -- --hostname 0.0.0.0 --port 3000
    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: hunty
      POSTGRES_PASSWORD: hunty
      POSTGRES_DB: hunty_dev
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
